Repository kakao-tech-campus-2nd-step3/Team6_FE, pull requests merged in 2024-10, with the labels that each got.

#44 Week5/issue#40 그룹 섹션 UI 구현
  src/components/features/Layout/GroupSection/GroupHeader/index.tsx
  src/components/features/Layout/GroupSection/GroupList/GroupListItem/index.tsx
  src/components/features/Layout/GroupSection/GroupList/index.tsx
  src/components/features/Layout/GroupSection/index.tsx
  src/stores/selected-group.ts
  src/types/index.ts
Labels: 🎨 UI

#48 Week5/issue#43 프로필 버튼 그리드 재사용하도록 수정
  src/pages/MainPage/ProfileButton/index.tsx
  src/pages/MainPage/ProfileGrid/index.tsx
  src/pages/MainPage/Question/index.tsx
  src/pages/MainPage/SkipReloadButton/index.tsx
  src/pages/MainPage/index.tsx
Labels: 🛠️ fix, 쿠키 주기 & 쿠키 받기

#52 Week5/issue#28 채팅 컴포넌트 구현
  src/components/common/ChatBox/index.tsx
Labels: 🌟 feature, 프로필 & 프로필 질문

#57 Week5/issue#56 카드 컴포넌트 설명 부분 수정
  src/components/common/CardButton/index.tsx
Labels: 🛠️ fix

#55 Week5/issue#51 그룹 페이지 UI 구현
  src/pages/GroupPage/Management/index.tsx
  src/pages/GroupPage/Navigate/index.tsx
  src/pages/GroupPage/Profile/index.tsx
  src/pages/GroupPage/index.tsx
  src/routes/index.tsx
Labels: 🎨 UI, 그룹

#61 Week6/issue#60 axios 추가 및 api 세팅
  .gitignore
  package-lock.json
  package.json
  src/App.tsx
  src/api/instance/index.ts
Labels: ⚙️ setting

#68 Week6/issue#65 404 not found error page UI 구현
  src/pages/ErrorPage/index.tsx
  src/routes/index.tsx
Labels: 🎨 UI

#63 Week6/issue#62 타입 단언 제거
  src/components/common/CardButton/index.tsx
  src/pages/GroupPage/Management/index.tsx
Labels: 🛠️ fix

#71 Week6/issue#66 로딩 컴포넌트 구현
  src/components/common/Loading/index.tsx
Labels: 🌟 feature

#70 Week6/issue#53 프로필 Q&A 페이지 UI 구현
  src/components/common/ChatBox/index.tsx
  src/components/features/Layout/ActiveBrownBox/index.tsx
  src/components/features/Layout/ProfileQuestionLayout/QuestionList/index.tsx
  src/components/features/Layout/ProfileQuestionLayout/QuestionSection/index.tsx
  src/components/features/Layout/ProfileQuestionLayout/index.tsx
  src/pages/MyPage/OvenMenu/index.tsx
  src/pages/ProfileQuestionPage/Answer/index.tsx
  src/pages/ProfileQuestionPage/Question/index.tsx
  src/pages/ProfileQuestionPage/WriteReply/index.tsx
  src/pages/ProfileQuestionPage/index.tsx
  src/stores/selected-question.ts
  src/types/index.ts
Labels: 🌟 feature, 프로필 & 프로필 질문

#67 Week6/issue#35 로그인 기능 추가
  src/api/instance/index.ts
  src/api/services/login/index.ts
  src/assets/kakao-logo-symbol.svg
  src/components/common/PageLayout/SideNavigation/index.tsx
  src/constants/errorMessage.ts
  src/pages/LoginPage/KakaoLoginButton/index.tsx
  src/pages/LoginPage/index.tsx
  src/pages/LoginRedirectPage/LoginRedirectSection/index.tsx
  src/pages/LoginRedirectPage/index.tsx
  src/routes/ProtectedRoute/index.tsx
  src/routes/index.tsx
  src/stores/auth-token.ts
  src/styles/font.ts
Labels: 🌟 feature

#73 Week6/issue#72 폴더구조 리팩토링
  src/api/services/login/index.ts
  src/components/ActiveBrownBox/index.tsx
  src/components/AvatarLabel/index.tsx
  src/components/CardButton/index.tsx
  src/components/ChatBox/index.tsx
  src/components/Loading/index.tsx
  src/components/LogText/HintIcon/index.tsx
  src/components/LogText/index.tsx
  src/components/Modal/AlertModal/index.tsx
  src/components/Modal/ConfirmModal/index.tsx
  src/components/Modal/FormModal/index.tsx
  src/components/Modal/TestModal/index.tsx
  src/components/PageLayout/Footer/index.tsx
  src/components/PageLayout/SideNavigation/index.tsx
  src/components/PageLayout/SideSection/index.tsx
  src/components/PageLayout/index.tsx
  src/components/RankingGraph/index.tsx
  src/components/features/Layout/MainLayout/AvatarLabel/index.tsx
  src/constants/error-message.ts
  src/main.tsx
  src/pages/GroupPage/Management/index.tsx
  src/pages/GroupPage/index.tsx
  src/pages/Layout/MainLayout/GroupSection/GroupList/index.tsx
  src/pages/Layout/MainLayout/GroupSection/index.tsx
  src/pages/Layout/MainLayout/MemberSection/FriendSection/FriendHeader/index.tsx
  src/pages/Layout/MainLayout/MemberSection/FriendSection/FriendList/index.tsx
  src/pages/Layout/MainLayout/MemberSection/FriendSection/index.tsx
  src/pages/Layout/MainLayout/MemberSection/SelectFriendSection/KakaoFriendList/KakaoFriendListItem/index.tsx
  src/pages/Layout/MainLayout/MemberSection/SelectFriendSection/KakaoFriendList/index.tsx
  src/pages/Layout/MainLayout/MemberSection/SelectFriendSection/SelectFriendHeader/index.tsx
  src/pages/Layout/MainLayout/MemberSection/SelectFriendSection/index.tsx
  src/pages/Layout/MainLayout/MemberSection/index.tsx
  src/pages/Layout/MainLayout/index.tsx
  src/pages/Layout/ProfileQuestionLayout/QuestionList/index.tsx
  src/pages/Layout/ProfileQuestionLayout/QuestionSection/index.tsx
  src/pages/Layout/ProfileQuestionLayout/index.tsx
  src/pages/LoginRedirectPage/LoginRedirectSection/index.tsx
  src/pages/MyPage/OvenMenu/index.tsx
  src/pages/MyPage/index.tsx
  src/pages/ProfileQuestionPage/Answer/index.tsx
  src/pages/ProfileQuestionPage/Question/index.tsx
  src/routes/index.tsx
  src/stores/selected-group.ts
  src/styles/index.css
Labels: ♻️ refactor

#82 Week7/issue#26 마이페이지 기능 구현
  README.md
  src/api/services/profile/mypage/index.ts
  src/api/services/profile/mypage/useMyPage.ts
  src/pages/MyPage/Profile/index.tsx
  src/pages/MyPage/index.tsx
  src/routes/index.tsx
  src/types/index.ts
Labels: 🌟 feature, 프로필 & 프로필 질문

#80 Week7/issue#31 쿠키 주기 (메인) 기능 구현
  src/api/services/answer/common/index.ts
  src/api/services/answer/common/useAnswerQuestion.ts
  src/api/services/friend/index.ts
  src/api/services/friend/useKakaoFriends.ts
  src/api/services/question/random/index.ts
  src/api/services/question/random/useRandomQuestion.ts
  src/pages/MainPage/ProfileButton/index.tsx
  src/pages/MainPage/ProfileGrid/index.tsx
  src/pages/MainPage/Question/index.tsx
  src/pages/MainPage/SkipReloadButton/index.tsx
  src/pages/MainPage/index.tsx
  src/types/index.ts
Labels: 🌟 feature, 쿠키 주기 & 쿠키 받기

#87 Week9/issue#86 공통 에러 핸들링
  src/api/instance/auth-error-interceptor.ts
  src/api/instance/index.ts
  src/api/services/answer/common/index.ts
  src/api/services/answer/record-paging/index.ts
  src/api/services/friend/index.ts
  src/api/services/login/index.ts
  src/api/services/profile/mypage/index.ts
  src/api/services/question/random/index.ts
  src/components/PageLayout/index.tsx
  src/constants/error-message.ts
  src/pages/CookieRecordPage/CookieRecordErrorFallback/index.tsx
  src/pages/CookieRecordPage/LogSection/index.tsx
  src/pages/Layout/MainLayout/GlobalErrorFallback/ErrorButton/index.tsx
  src/pages/Layout/MainLayout/GlobalErrorFallback/index.tsx
  src/pages/Layout/MainLayout/GroupSection/index.tsx
  src/pages/Layout/MainLayout/MemberSection/FriendSection/index.tsx
  src/pages/Layout/MainLayout/index.tsx
Labels: 🌟 feature
