Repository kakao-tech-campus-2nd-step3/Team6_FE, pull requests merged in 2024-11, with the labels that each got.

#91 Week9/issue#90 나의 userId 저장하기
  src/api/instance/auth-error-interceptor.ts
  src/api/services/login/index.ts
  src/components/PageLayout/SideNavigation/index.tsx
  src/pages/LoginRedirectPage/LoginRedirectSection/index.tsx
  src/stores/my-user-id.ts
Labels: 🌟 feature

#93 Week9/issue#88 그룹 섹션 기능 추가
  src/api/instance/auth-error-interceptor.ts
  src/api/instance/index.ts
  src/api/services/answer/common/index.ts
  src/api/services/answer/record-paging/index.ts
  src/api/services/answer/record-paging/useAnswerRecordPaging.ts
  src/api/services/friend/index.ts
  src/api/services/group/index.ts
  src/api/services/group/useGroupPaging.ts
  src/api/services/login/index.ts
  src/api/services/profile/mypage/index.ts
  src/api/services/question/random/index.ts
  src/api/utils/common/getPagingPath.ts
  src/components/PageLayout/SideSection/index.tsx
  src/components/PageLayout/index.tsx
  src/constants/error-message.ts
  src/pages/CookieRecordPage/CookieRecordErrorFallback/index.tsx
  src/pages/CookieRecordPage/LogSection/index.tsx
  src/pages/Layout/MainLayout/GlobalErrorFallback/ErrorButton/index.tsx
  src/pages/Layout/MainLayout/GlobalErrorFallback/index.tsx
  src/pages/Layout/MainLayout/GroupSection/AddGroupButton/index.tsx
  src/pages/Layout/MainLayout/GroupSection/GroupErrorFallback/index.tsx
  src/pages/Layout/MainLayout/GroupSection/GroupList/index.tsx
  src/pages/Layout/MainLayout/GroupSection/index.tsx
  src/pages/Layout/MainLayout/MemberSection/FriendSection/index.tsx
  src/pages/Layout/MainLayout/index.tsx
  src/pages/MyPage/Profile/index.tsx
  src/types/index.ts
Labels: 🌟 feature

#92 Week9/issue#31 쿠키주기(메인)기능 수정
  src/api/services/answer/common/index.ts
  src/api/services/answer/common/useAnswerQuestion.ts
  src/pages/MainPage/ProfileGrid/index.tsx
  src/pages/MainPage/Question/index.tsx
  src/pages/MainPage/SkipReloadButton/index.tsx
  src/pages/MainPage/UseProfilehook/index.ts
  src/pages/MainPage/index.tsx
Labels: 🛠️ fix, 쿠키 주기 & 쿠키 받기

#99 Week9/issue#97 api 구조 변경
  src/api/services/answer/question.api.ts
  src/api/services/answer/record-paging/index.ts
  src/api/services/answer/record-paging/useAnswerRecordPaging.ts
  src/api/services/answer/record.api.ts
  src/api/services/friend/friend.api.ts
  src/api/services/friend/queries.ts
  src/api/services/friend/useKakaoFriends.ts
  src/api/services/group/group.api.ts
  src/api/services/group/index.ts
  src/api/services/group/useGroupPaging.ts
  src/api/services/profile/my-page.api.ts
  src/api/services/profile/mypage/index.ts
  src/api/services/profile/mypage/useMyPage.ts
  src/api/services/question/random.api.ts
  src/api/services/question/random/index.ts
  src/api/services/question/random/useRandomQuestion.ts
  src/api/services/user/login.api.ts
  src/pages/CookieRecordPage/LogSection/index.tsx
  src/pages/Layout/MainLayout/GroupSection/GroupList/index.tsx
  src/pages/Layout/MainLayout/MemberSection/FriendSection/index.tsx
  src/pages/Layout/MainLayout/MemberSection/SelectFriendSection/SelectFriendHeader/index.tsx
  src/pages/Layout/MainLayout/MemberSection/SelectFriendSection/index.tsx
  src/pages/LoginRedirectPage/LoginRedirectSection/index.tsx
  src/pages/MainPage/Question/index.tsx
  src/pages/MainPage/UseProfilehook/index.ts
  src/pages/MainPage/index.tsx
  src/pages/MyPage/index.tsx
  src/types/index.ts
Labels: ♻️ refactor

#100 Week10/issue#95 힌트 사용하기
  src/api/services/answer/hint.api.ts
  src/api/services/answer/record.api.ts
  src/api/services/group/group.api.ts
  src/api/services/user/point.api.ts
  src/api/utils/common/appendParamsToUrl.ts
  src/api/utils/common/getPagingPath.ts
  src/components/CookieLogText/index.tsx
  src/components/PageLayout/index.tsx
  src/hooks/useClickOutsideElement.ts
  src/pages/CookieRecordPage/HintDrawer/AnswerDetail/index.tsx
  src/pages/CookieRecordPage/HintDrawer/BuyHintModal/index.tsx
  src/pages/CookieRecordPage/HintDrawer/HintList/index.tsx
  src/pages/CookieRecordPage/HintDrawer/MyPoint/index.tsx
  src/pages/CookieRecordPage/HintDrawer/index.tsx
  src/pages/CookieRecordPage/LogSection/CookieLogList/index.tsx
  src/pages/CookieRecordPage/LogSection/index.tsx
  src/stores/selected-answer.ts
  src/types/index.ts
Labels: 🌟 feature

#106 Week10/issue#101 그룹 생성하기
  .eslintrc.cjs
  package-lock.json
  package.json
  src/api/services/group/group.api.ts
  src/components/Form/FormContext.tsx
  src/components/Form/FormProvider.tsx
  src/components/Form/index.tsx
  src/pages/CreateGroupPage/CreateGroupForm/ImageInput/index.tsx
  src/pages/CreateGroupPage/CreateGroupForm/index.tsx
  src/pages/CreateGroupPage/index.tsx
  src/pages/Layout/MainLayout/GroupSection/AddGroupButton/index.tsx
  src/pages/Layout/MainLayout/GroupSection/CreateGroupButton/index.tsx
  src/pages/Layout/MainLayout/GroupSection/GroupList/index.tsx
  src/pages/Layout/MainLayout/GroupSection/index.tsx
  src/routes/index.tsx
  src/schema/create-group.ts
  src/types/index.ts
Labels: 🌟 feature

#109 Week10/issue#98 그룹 정보 조회, 수정하기
  src/api/services/group/group.api.ts
  src/pages/GroupPage/Profile/index.tsx
  src/pages/GroupPage/index.tsx
  src/routes/index.tsx
Labels: 🌟 feature, 그룹

#114 Week10/issue#112 그룹 멤버 섹션
  src/api/services/group/member.api.ts
  src/constants/error-message.ts
  src/pages/Layout/MainLayout/GroupSection/GroupList/index.tsx
  src/pages/Layout/MainLayout/GroupSection/index.tsx
  src/pages/Layout/MainLayout/MemberSection/GroupMemberSection/index.tsx
  src/pages/Layout/MainLayout/MemberSection/MemberErrorFallback/index.tsx
  src/pages/Layout/MainLayout/MemberSection/index.tsx
  src/stores/selected-group.ts
  src/types/index.ts
Labels: 🌟 feature, ♻️ refactor

#115 Week10/issue#89 프로필 질문 API 연결 및 기능 구현
  .github/workflows/main.yml
  src/api/services/profile/my-page.api.ts
  src/api/services/profile/profile-question.api.ts
  src/components/CardButton/index.tsx
  src/components/ChatBox/index.tsx
  src/components/PageLayout/SideNavigation/index.tsx
  src/pages/Layout/ProfileQuestionLayout/CreateQuestionButton/index.tsx
  src/pages/Layout/ProfileQuestionLayout/QuestionList/index.tsx
  src/pages/Layout/ProfileQuestionLayout/QuestionSection/index.tsx
  src/pages/MyPage/Navigate/index.tsx
  src/pages/MyPage/OvenMenu/index.tsx
  src/pages/MyPage/Profile/index.tsx
  src/pages/MyPage/index.tsx
  src/pages/ProfileQuestionPage/Answer/formatDate.tsx
  src/pages/ProfileQuestionPage/Answer/index.tsx
  src/pages/ProfileQuestionPage/Question/index.tsx
  src/pages/ProfileQuestionPage/WriteReply/index.tsx
  src/pages/ProfileQuestionPage/index.tsx
  src/stores/selected-question.ts
  src/types/index.ts
Labels: 🌟 feature, 프로필 & 프로필 질문

#122 Week10/issue#118 프로필 수정 및 랭킹 조회
  src/api/services/profile/my-page.api.ts
  src/api/services/profile/profile-question.api.ts
  src/assets/cookie1.svg
  src/assets/cookie2.svg
  src/assets/cookie3.svg
  src/components/RankingGraph/index.tsx
  src/pages/MyPage/Profile/index.tsx
  src/pages/MyPage/Ranking/index.tsx
  src/pages/MyPage/index.tsx
  src/types/index.ts
Labels: 🌟 feature, 프로필 & 프로필 질문

#117 Week10/issue#116 그룹 멤버 초대하기
  src/api/services/group/group.api.ts
  src/api/services/group/member.api.ts
  src/api/services/profile/my-page.api.ts
  src/api/utils/common/appendParamsToUrl.ts
  src/assets/cookies.svg
  src/assets/whokie.svg
  src/components/CardButton/index.tsx
  src/components/PageLayout/index.tsx
  src/components/RankingGraph/index.tsx
  src/pages/ErrorPage/index.tsx
  src/pages/GroupPage/Management/InviteMemberModal/index.tsx
  src/pages/GroupPage/Management/index.tsx
  src/pages/GroupPage/Profile/EditProfile/index.tsx
  src/pages/GroupPage/Profile/index.tsx
  src/pages/GroupPage/index.tsx
  src/pages/InvitePage/InviteCard/index.tsx
  src/pages/InvitePage/InviteErrorFallback/ErrorModal/index.tsx
  src/pages/InvitePage/InviteErrorFallback/index.tsx
  src/pages/InvitePage/index.tsx
  src/pages/Layout/CardLayout/index.tsx
  src/pages/Layout/MainLayout/GroupSection/GroupList/index.tsx
  src/pages/Layout/MainLayout/GroupSection/index.tsx
  src/pages/Layout/MainLayout/MemberSection/GroupMemberSection/index.tsx
  src/pages/MyPage/OvenMenu/index.tsx
  src/pages/MyPage/Ranking/index.tsx
  src/routes/index.tsx
  src/types/index.ts
Labels: 🌟 feature, ♻️ refactor, 그룹

#135 Week10/issue#133 그룹 나가기
  src/api/services/group/member.api.ts
  src/pages/GroupPage/ExitGroupButton/index.tsx
  src/pages/GroupPage/Management/index.tsx
  src/pages/GroupPage/Profile/index.tsx
  src/pages/GroupPage/index.tsx
  src/types/index.ts
Labels: 🌟 feature, 그룹

#136 Week10/issue#124 그룹 멤버 관리 페이지 API 연결
  .github/workflows/main.yml
  src/api/services/group/member.api.ts
  src/pages/GroupMembersPage/ExpelBtn/index.tsx
  src/pages/GroupMembersPage/MembersTable/index.tsx
  src/pages/GroupMembersPage/Pagination/index.tsx
  src/pages/GroupMembersPage/Title/index.tsx
  src/pages/GroupMembersPage/index.tsx
  src/pages/GroupPage/Management/index.tsx
  src/pages/GroupPage/index.tsx
  src/pages/ProfileQuestionPage/Answer/index.tsx
  src/types/index.ts
Labels: 🌟 feature, 그룹

#138 Week10/issue#137 쿠키 주기 버그 수정
  src/api/services/group/member.api.ts
  src/pages/GroupPage/ExitGroupButton/index.tsx
  src/pages/GroupPage/Management/index.tsx
  src/pages/GroupPage/Profile/index.tsx
  src/pages/GroupPage/index.tsx
  src/pages/Layout/MainLayout/MemberSection/SelectFriendSection/SelectFriendHeader/index.tsx
  src/pages/MainPage/UseProfilehook/index.ts
  src/types/index.ts
Labels: 🛠️ fix

#147 Week10/issue#140 그룹장 위임하기
  src/api/services/group/member.api.ts
  src/pages/GroupMembersPage/ExpelBtn/index.tsx
  src/pages/GroupMembersPage/LeaderChangeBtn/index.tsx
  src/pages/GroupMembersPage/MembersTable/index.tsx
  src/pages/GroupMembersPage/index.tsx
  src/pages/GroupPage/Management/index.tsx
Labels: 🌟 feature, 그룹, 멤버

#149 Week10/issue#148 그룹 멤버 관리 페이지 테이블 버그 수정
  src/pages/GroupMembersPage/MembersTable/TableComponent/index.tsx
  src/pages/GroupMembersPage/MembersTable/index.tsx
  src/types/index.ts
Labels: 🛠️ fix, 그룹, 멤버

#152 Week10/issue#143 랭킹 없을 때 프로필 UI 구현
  src/assets/sadCookie.svg
  src/pages/GroupPage/index.tsx
  src/pages/MyPage/Ranking/index.tsx
Labels: 🎨 UI, 프로필 & 프로필 질문

#131 Week10/issue#130 그룹 질문 생성 API 연결 및 기능 구현
  src/api/services/question/group.api.ts
  src/pages/GroupPage/Management/CreateQuestion/index.tsx
  src/pages/GroupPage/Management/Questions/index.tsx
  src/pages/GroupPage/Management/index.tsx
  src/pages/GroupQuestionPage/Question/index.tsx
  src/pages/GroupQuestionPage/index.tsx
  src/routes/index.tsx
Labels: 🌟 feature, 그룹

#172 Week10/issue#169 eslint 에러 해결, 질문 관리 텍스트 추가
  src/api/services/group/group.api.ts
  src/api/services/question/group.api.ts
  src/pages/GroupPage/Management/Questions/QuestionList/index.tsx
  src/pages/GroupPage/Management/Questions/StatusButton/index.tsx
  src/pages/GroupPage/Management/Questions/index.tsx
  src/routes/index.tsx
Labels: 🛠️ fix

#178 Week10/issue#173 그룹 관리 페이지, 그룹 질문 관리 페이지 로딩 및 권한 체크 버그 수정
  src/pages/GroupMembersPage/LeaderChangeBtn/index.tsx
  src/pages/GroupMembersPage/MembersTable/TableComponent/index.tsx
  src/pages/GroupMembersPage/MembersTable/index.tsx
  src/pages/GroupMembersPage/index.tsx
  src/pages/GroupPage/Management/Questions/index.tsx
Labels: 🌟 feature, 🛠️ fix, 그룹, 멤버

#182 Week10/issue#181 그룹원 있을 때 그룹장 탈퇴 막기
  src/api/services/group/group.api.ts
  src/pages/GroupPage/ExitGroupButton/index.tsx
  src/pages/Layout/MainLayout/MemberSection/GroupMemberSection/index.tsx
  src/stores/members-length.ts
Labels: 🌟 feature, 그룹

#185 Week10/issue#184 그룹 생성 시 이미지 추가 삭제
  src/pages/CreateGroupPage/CreateGroupForm/ImageInput/index.tsx
  src/pages/CreateGroupPage/CreateGroupForm/index.tsx
  src/pages/CreateGroupPage/index.tsx
Labels: 🎨 UI, 그룹

#196 Week10/issue#168 그룹 이미지 수정
  src/api/services/group/group.api.ts
  src/pages/GroupPage/Profile/ImgModify/index.tsx
  src/pages/GroupPage/Profile/index.tsx
  src/types/index.ts
Labels: 🌟 feature, 그룹

#239 Week11/issue#221 profile question bug
  src/api/services/admin/admin.ts
  src/pages/Admin/GetQuestionAdminPage/index.tsx
  src/pages/Admin/index.tsx
  src/pages/Layout/ProfileQuestionLayout/CreateQuestionButton/index.tsx
  src/pages/Layout/ProfileQuestionLayout/QuestionList/index.tsx
  src/pages/ProfileQuestionPage/Answer/index.tsx
  src/pages/ProfileQuestionPage/Question/index.tsx
  src/pages/ProfileQuestionPage/WriteReply/index.tsx
  src/pages/ProfileQuestionPage/index.tsx
  src/routes/index.tsx
  src/stores/selected-question.ts
  src/types/index.ts
Labels: 🛠️ fix, 프로필 & 프로필 질문

#242 Week11/issue#235 member bug
  src/pages/GroupMembersPage/ExpelBtn/index.tsx
  src/pages/GroupPage/ExitGroupButton/index.tsx
Labels: 🛠️ fix, 멤버

#252 Week11/#issue251 member change bug
  README.md
  src/pages/CreateGroupPage/index.tsx
  src/pages/ProfileQuestionPage/Answer/index.tsx
Labels: 🛠️ fix, 멤버

#257 Week11/#issue255 그룹 초대 수락 시 멤버 렌더링 버그 수정
  src/pages/InvitePage/InviteCard/index.tsx
Labels: 🛠️ fix, 그룹
