Repository kakao-tech-campus-2nd-step3/Team6_FE, pull requests merged in 2024-09, with the labels that each got.

#15 Week3/issue#11 Chakra color theme 추가
  .eslintrc.cjs
  src/main.tsx
  src/styles/theme.ts
Labels: ⚙️ setting

#10 Week3/issue#7 로그 텍스트 컴포넌트 구현
  .eslintrc.cjs
  package-lock.json
  package.json
  src/components/common/LogText/HintIcon/index.tsx
  src/components/common/LogText/index.tsx
Labels: 🌟 feature, 🎨 UI

#14 Week3/issue#8 랭킹 그래프 컴포넌트 구현
  package-lock.json
  src/components/common/RankingGraph/index.tsx
Labels: 🌟 feature, 🎨 UI

#13 Week3/issue#12 모달 컴포넌트 구현
  src/components/common/Modal/AlertModal/index.tsx
  src/components/common/Modal/ConfirmModal/index.tsx
  src/components/common/Modal/FormModal/index.tsx
  src/components/common/Modal/TestModal/index.tsx
Labels: 🌟 feature, 🎨 UI

#16 Week3/issue#9 카드 버튼 컴포넌트 구현
  package-lock.json
  src/components/common/CardButton/index.tsx
Labels: 🌟 feature, 🎨 UI

#20 Week3/issue#11 프로젝트 세팅 추가
  .eslintrc.cjs
  .prettierrc
  package-lock.json
  package.json
  src/App.tsx
  src/api/instance/index.ts
  src/main.tsx
  src/pages/MainPage/index.tsx
  src/pages/MyPage/index.tsx
  src/routes/index.tsx
  tsconfig.app.json
  vite.config.ts
Labels: ⚙️ setting

#32 Week4/issue#29 폰트 적용하기
  .eslintrc.cjs
  index.html
  src/styles/font.ts
  src/styles/theme.ts
Labels: ⚙️ setting

#34 Week4/issue#23 멤버 목록 UI 구현하기
  .eslintrc.cjs
  .prettierrc
  src/components/features/Layout/FriendSection/index.tsx
  src/components/features/Layout/MemberSection/FriendSection/FriendHeader/index.tsx
  src/components/features/Layout/MemberSection/FriendSection/FriendList/index.tsx
  src/components/features/Layout/MemberSection/FriendSection/index.tsx
  src/components/features/Layout/MemberSection/SelectFriendSection/KakaoFriendList/KakaoFriendListItem/index.tsx
  src/components/features/Layout/MemberSection/SelectFriendSection/KakaoFriendList/index.tsx
  src/components/features/Layout/MemberSection/SelectFriendSection/SelectFriendHeader/index.tsx
  src/components/features/Layout/MemberSection/SelectFriendSection/index.tsx
  src/components/features/Layout/MemberSection/index.tsx
  src/components/features/Layout/index.tsx
  src/index.css
  src/stores/member-type.ts
  src/types/index.ts
Labels: 🌟 feature, 🎨 UI, 멤버

#37 Week4/issue#36 카드 버튼 컴포넌트 수정
  package-lock.json
  src/components/common/CardButton/index.tsx
  src/pages/MainPage/index.tsx
Labels: 🛠️ fix

#38 Week4/issue#24 마이페이지 UI 구현하기
  src/components/common/RankingGraph/index.tsx
  src/components/features/Layout/index.tsx
  src/pages/MyPage/Navigate/index.tsx
  src/pages/MyPage/OvenMenu/index.tsx
  src/pages/MyPage/Profile/index.tsx
  src/pages/MyPage/index.tsx
Labels: 🎨 UI, 프로필 & 프로필 질문

#39 Week4/issue#21 props 타입 지정 interface로 통일
  src/components/common/LogText/HintIcon/index.tsx
  src/components/common/LogText/index.tsx
  src/components/common/Modal/AlertModal/index.tsx
  src/components/common/Modal/ConfirmModal/index.tsx
  src/components/common/Modal/FormModal/index.tsx
  src/components/common/RankingGraph/index.tsx
Labels: 🛠️ fix
